### ISSUE TITLE
TypeError: Can't instantiate abstract class HBaseBackend with abstract methods finished, links_extracted

### ISSUE THREAD

**Issue by viktor0710** [scrapinghub/distributed-frontera#26]
Hello,

After following all the instructions from the docs: http://distributed-frontera.readthedocs.io/en/latest/topics/quickstart.html

I get the following error when starting the DB worker:

[cloudera@quickstart general-spider]$ python -m distributed_frontera.worker.main --config frontier.workersettings
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/distributed_frontera/worker/main.py", line 226, in <module>
    worker = FrontierWorker(settings, args.no_batches, args.no_scoring, args.no_incoming)
  File "/usr/local/lib/python2.7/site-packages/distributed_frontera/worker/main.py", line 69, in __init__
    self._manager = FrontierManager.from_settings(settings)
  File "/usr/local/lib/python2.7/site-packages/frontera/core/manager.py", line 284, in from_settings
    strategy_worker=strategy_worker)
  File "/usr/local/lib/python2.7/site-packages/frontera/core/manager.py", line 245, in __init__
    strategy_worker=strategy_worker)
  File "/usr/local/lib/python2.7/site-packages/frontera/core/manager.py", line 27, in __init__
    self._backend = self._load_backend(backend, db_worker, strategy_worker)
  File "/usr/local/lib/python2.7/site-packages/frontera/core/manager.py", line 65, in _load_backend
    return cls.from_manager(self)
  File "/usr/local/lib/python2.7/site-packages/distributed_frontera/backends/hbase.py", line 341, in from_manager
    return cls(manager)
TypeError: Can't instantiate abstract class HBaseBackend with abstract methods finished, links_extracted

**Comment by sibiryakov** [comment]
Hey @viktor0710 distributed-frontera was merged to Frontera some time ago, so please use HBaseBackend class from Frontera framework.
