### ISSUE TITLE
Why is "TypeError" being raised? - Unable to debug the cause

### ISSUE THREAD

**Issue by stejesh** [scrapinghub/distributed-frontera#6]
I've installed kafka, zookeeperd is running fine.

and then I created the kafka topics as per the docs
```sh
kafka-topics.sh --create --topic frontier-todo --replication-factor 1 --partitions 2 --zookeeper localhost:2181
$ kafka-topics.sh --create --topic frontier-done --replication-factor 1 --partitions 2 --zookeeper localhost:2181
$ kafka-topics.sh --create --topic frontier-score --replication-factor 1 --partitions 1 --zookeeper localhost:2181
```

To confirm if they've been created, I ran `kafkat partitions` and it shows the topics created

```sh
Topic		Partition	Leader		Replicas						ISRs				
TutorialTopic	0		0		[0]							[0]				
frontier-score	0		0		[0]							[0]				
frontier-todo	0		0		[0]							[0]				
frontier-todo	1		0		[0]							[0]				
frontier-done	0		0		[0]							[0]				
frontier-done	1		0		[0]							[0]		
```		

After that, while starting the DB Worker

on running

` python -m distributed_frontera.worker.main --config crawler.settings`

I get the following error

```sh
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tejesh/projects/billionleads/python/python2.7-env/lib/python2.7/site-packages/distributed_frontera/worker/main.py", line 237, in <module>
    worker = FrontierWorker(settings, args.no_batches, args.no_scoring, args.no_incoming)
  File "/home/tejesh/projects/billionleads/python/python2.7-env/lib/python2.7/site-packages/distributed_frontera/worker/main.py", line 70, in __init__
    max_buffer_size=10485760)
  File "/home/tejesh/projects/billionleads/python/python2.7-env/local/lib/python2.7/site-packages/kafka/consumer/simple.py", line 126, in __init__
    auto_commit_every_t=auto_commit_every_t)
  File "/home/tejesh/projects/billionleads/python/python2.7-env/local/lib/python2.7/site-packages/kafka/consumer/base.py", line 49, in __init__
    self.topic = kafka_bytestring(topic)
  File "/home/tejesh/projects/billionleads/python/python2.7-env/local/lib/python2.7/site-packages/kafka/util.py", line 101, in kafka_bytestring
    raise TypeError(s)
TypeError: None
```

Basically `TypeError` is raised and i'm unable to debug this.

What seems to be the issue?

I've even tried testing kafka by sending messages
`echo "Hello, World" | ~/kafka/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic TutorialTopic > /dev/null`

and it's working fine.

How should i proceed in this issue?

**Comment by sibiryakov** [comment]
Hey, probably ``INCOMING_TOPIC`` (check also ``FRONTIER_GROUP``) is missing in your crawler.config. But I'm not sure, please post ``crawler.config`` contents here, if this is not the issue.

**Comment by stejesh** [comment]
@sibiryakov 

Ah, Fixed that, But then I get this issue when firing up the strategy worker,

`python -m distributed_frontera.worker.score --config crawler.frontera.strategy
_list.strategy0 --strategy distributed_frontera.worker.strategy.bfs`

Apparently `No module named crawlfrontier.contrib.canonicalsolvers.basic`

**Full Traceback**
```sh
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tejesh/projects/billionleads/python/python2.7-env/lib/python2.7/site-packages/distributed_frontera/worker/score.py", line 207, in <module>
    strategy_module = import_module(args.strategy)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tejesh/projects/billionleads/python/python2.7-env/local/lib/python2.7/site-packages/distributed_frontera/worker/strategy/bfs.py", line 3, in <module>
    from crawlfrontier.contrib.canonicalsolvers.basic import BasicCanonicalSolver
ImportError: No module named crawlfrontier.contrib.canonicalsolvers.basic
```

**Comment by sibiryakov** [comment]
@stejesh Your import fixes seems to be fine. 
Partitioning-related error probably caused by outdated kafka-python module. Please make sure you have the latest one.

**Comment by stejesh** [comment]
Ah, The error apparently was because `pip install distributed_frontera`  installs a different (older) version than cloning this git repository and installing

Either way, Thanks. kafka-python is the latest and running.

The spider works well in single-threaded(frontera) mode. 

However while running in distributed_frontera. I'm able to get the SW, DB worker and the spider running

but It only seems to process the `start_urls`  within the scrapy spider. 

I'm using the `CrawlSpider` in scrapy. The new regex-matching(link extractory) links appear not to be extracted/crawled, However they are extracted & crawled in frontera mode

Full Output here ->  http://pastebin.com/9ahh9zfa

Spider `settings0.py` file -> http://pastebin.com/tGckc2F8
SW config -> `Strategy0.py` -> http://pastebin.com/h5Xj8z08
DB worker config -> `worker_settings.py` -> http://pastebin.com/VJSEnp33

You can see the partitions created on the first posting in this page

Do you have any suggestions?

**Comment by sibiryakov** [comment]
Hey @stejesh, great!
I need more information:
 - you use ``distributed_frontera.worker.strategy.bfs`` when running SW?
 - please post here output of SW and DB after spider made ``add_seeds`` calls,
 - please run the experiment at least for few minutes, DB generates new batches periodically, with some delay,
 - post your spider code also,

A.

**Comment by stejesh** [comment]
@sibiryakov 

Yes, I'm using the copied code from `distributed_frontera.worker.strategy.bfs` + implementing the `finsihed()` method
as my `strategy0.py` file

(added some `print` statements to debug)
**Strategy0 Code:** http://pastebin.com/ynp1Ls9X 



I'm running it this way (both `--config` and `--strategy` point to same file)
```sh
python -m distributed_frontera.worker.score --config crawler.frontera.strategy_list.strategy0 --strategy crawler.frontera.strategy_list.strategy0
```

instead of command specified in the docs below
```sh
python -m distributed_frontera.worker.score --config crawler.frontera.strategy_list.strategy0 --strategy distributed_frontera.worker.strategy.bfs
```

Because i get a "can't instantiate abstract class" error when done by the docs
```sh
/distributed_frontera/worker/score.py", line 39, in __init__
    self.strategy = strategy_module.CrawlingStrategy()
TypeError: Can't instantiate abstract class CrawlingStrategy with abstract methods finished
```

The `finished()` method is abstract, and i cannot pass `distributed_frontera.worker.strategy.bfs` as --strategy

**Full Spider Output here:** http://pastebin.com/SLtbvD5E

I'm getting a lot of Timeout errors on distributed_frontera, this does not happen in frontera mode
```sh
[backend] Timeout (5.0 seconds) while trying to get 256 requests
2015-09-22 12:18:31 [backend] WARNING: Timeout (5.0 seconds) while trying to get 256 requests
```

**Spider Code:** http://pastebin.com/8tC4YK1z

**SW output:**  http://pastebin.com/L0QnYjgr

**DB output:**  http://pastebin.com/J7ictTAE

**Comment by sibiryakov** [comment]
@stejesh 
This tells me SW doesn't schedules seed for download
> $$ inside add_seeds : seeds -> [<Request at 0xb5c63e2c > http://www.consumercomplaints.in/lastcompanieslist/page/4>], scores -> {}

Probably it was downloaded during one of the previous runs. I would like you too set ``HBASE_DROP_ALL_TABLES `` to ``True`` in SW config. Then if SW keeps producing empty ``scores`` dicts in add_seeds please print ``seed.meta`` contents and post here.

I see nothing suspicious except that. Your seed urls doesn't scheduling because SW isn't sending scores for them, and looking to the code says it's probably because of state checking.

**Comment by stejesh** [comment]
@sibiryakov 

Made those suggested changes, scores are now being generated.

here is the full **SW output:** http://pastebin.com/C3jVKfkf

It does'nt crawl all the links because a lot of them are timed-out & not retried and hence new links not extracted (by LinkExtractor)

 for comparison, take a look at the same spider run in frontera mode. **here:** http://pastebin.com/WdsAAZDN

It crawls at the rate of 120 pages/min

distributed_frontera is doing like 1 request every 2 seconds for every crawl and timing out eventually resulting in only a tiny amount of the total links being crawled.


Do you have suggestions to deal with the above?

**Comment by sibiryakov** [comment]
@stejesh it looks like system is set up now! We have closed data flow. 
Now it needs to be adjusted and tuned a bit.
I need to know two things:
 - what is overall problem you're trying to solve?
 - post your Scrapy settings please for both Frontera and Distributed Frontera.

**Comment by stejesh** [comment]
@sibiryakov 

My objectives are,

- For distriubted_frontera to give best possible performance in terms of requests/minute atleast upto single threaded frontera

These are the **Frontera/settings.py** : http://pastebin.com/yc77FLrf which give a fast performance output **here** http://pastebin.com/WdsAAZDN


Regarding distributed_frontera,


- This is the spider **settings0.py** : http://pastebin.com/nmzEknFU for distributed_frontera

- **DB worker** : http://pastebin.com/B9ZVETNr

- **SW worker**: http://pastebin.com/NtvB47FH

**Comment by stejesh** [comment]
Hi @sibiryakov 

Thank you for your support, I wonder if you have any updates :)

If finding out the root cause of the slow-down is hard, could you perhaps give me a configuration file instead that optimizes for speed in distibuted frontera in the above simple spider?

**Comment by sibiryakov** [comment]
@stejesh For some reason I wasn't notified for the previous message.

**Comment by sibiryakov** [comment]
@stejesh In distributed frontera mode when you run scrapy with ``-s FRONTERA_SETTINGS`` option scrapy takes two settings files:
 - settings.py in the scrapy project directory,
 - Frontera one supplied with FRONTERA_SETTINGS option.

Next, I'm going to talk only about first, Scrapy's file. I want to warn you that settings below, are causing spider to hit servers too hard. So be careful using them, and of course think of real users trying to use this website during your fetching activity.
 - Please make sure ``DOWNLOAD_TIMEOUT`` option is absent (so defaults should apply),
 - Set ``RANDOMIZE_DOWNLOAD_DELAY`` to ``False``,

That should give you increase in speed.
If you're still experiencing problems, please make a zip archive with your spider code or put it somewhere on github and post link here, so it would be much easier for me too to find out where the problem is.

**Comment by sibiryakov** [comment]
@stejesh So, guys do you have any more problems, suggestions?

**Comment by stejesh** [comment]
@sibiryakov I was'nt notified of this message strangely! 

Let me check this once more and get back to you

**Comment by stejesh** [comment]
Hello @sibiryakov 

I've made a git repo replicating this issue here https://github.com/stejesh/scrapy_project

Here is how i ran it,


Get into the directory
`cd scrapy_project`

Run the DB & SW worker

```sh
python -m distributed_frontera.worker.main --config crawler.crawler.frontier.worker_settings
python -m distributed_frontera.worker.score --config crawler.crawler.frontier.strategy_list.strategy0 --strategy crawler.crawler.frontier.strategy_list.strategy0
```

Run the spider with distributed_frontera
`scrapy crawl CustomSpider -s FRONTERA_SETTINGS=crawler.frontier.spider_settings.settings0`

Run the spider with frontera mode

`scrapy crawl CustomSpider`

On my side, the frontera mode is much much faster, (crawling and scraping data fill up the terminal fast)

on distributed_frontera however, it is very very slow, crawls a single link a second, and it halts suddenly giving a "finished" message.

I Hope there's something in there to tweak.

Thanks again,

**Comment by sibiryakov** [comment]
@stejesh I would love to see it in action. Could you manage me an ssh access to machine(s) where you running all that. E-mail me at sibiryakov[!!]scrapinghub.com.

**Comment by stejesh** [comment]
@sibiryakov Sure, will mail

**Comment by sibiryakov** [comment]
Also consider subscribing to Frontera mailing list
https://groups.google.com/forum/#!forum/frontera-ml

**Comment by sibiryakov** [comment]
@stejesh Please try message bus and ZeroMQ transport, also I changed the default requests distribution across spiders (now it's kind-of random) in master. These two things should address your needs.
